-- Themenkatalog Mathe, Klasse 5 bis 10 (Startdaten, keine Kinderdaten)
insert into public.thema (fach, name, klassenstufe_von, klassenstufe_bis, reihenfolge) values
  ('mathe', 'Natürliche Zahlen und Stellenwert',        5, 5, 10),
  ('mathe', 'Schriftliches Rechnen',                    5, 6, 20),
  ('mathe', 'Größen und Einheiten',                     5, 6, 30),
  ('mathe', 'Geometrische Grundbegriffe',               5, 6, 40),
  ('mathe', 'Brüche',                                   5, 6, 50),
  ('mathe', 'Dezimalzahlen',                            6, 6, 60),
  ('mathe', 'Teilbarkeit und Primzahlen',               5, 6, 70),
  ('mathe', 'Flächen und Umfang',                       5, 7, 80),
  ('mathe', 'Negative Zahlen',                          6, 7, 90),
  ('mathe', 'Prozentrechnung',                          7, 8, 100),
  ('mathe', 'Zuordnungen und Dreisatz',                 7, 7, 110),
  ('mathe', 'Terme und Variablen',                      7, 8, 120),
  ('mathe', 'Gleichungen lösen',                        7, 8, 130),
  ('mathe', 'Winkel und Dreiecke',                      7, 8, 140),
  ('mathe', 'Zinsrechnung',                             7, 8, 150),
  ('mathe', 'Wahrscheinlichkeit',                       7, 10, 160),
  ('mathe', 'Lineare Funktionen',                       8, 8, 170),
  ('mathe', 'Lineare Gleichungssysteme',                8, 9, 180),
  ('mathe', 'Binomische Formeln',                       8, 9, 190),
  ('mathe', 'Satz des Pythagoras',                      8, 9, 200),
  ('mathe', 'Körper und Volumen',                       8, 10, 210),
  ('mathe', 'Quadratische Funktionen',                  9, 10, 220),
  ('mathe', 'Quadratische Gleichungen',                 9, 10, 230),
  ('mathe', 'Wurzeln und Potenzen',                     9, 10, 240),
  ('mathe', 'Strahlensätze und Ähnlichkeit',            9, 10, 250),
  ('mathe', 'Trigonometrie',                            10, 10, 260),
  ('mathe', 'Exponentielles Wachstum',                  10, 10, 270),
  ('mathe', 'Daten und Statistik',                      5, 10, 280)
on conflict (fach, name) do nothing;
